name: Bio
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py38h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - anndata==0.9.2
      - anyio==4.5.2
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - bio==1.6.2
      - biopython==1.83
      - biothings-client==0.4.1
      - cachetools==5.5.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - exceptiongroup==1.2.2
      - filelock==3.16.1
      - flatbuffers==25.2.10
      - fonttools==4.54.1
      - formulaic==1.1.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.4.0
      - get-annotations==0.1.2
      - ghostscript==0.8.1
      - google-auth==2.39.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gprofiler-official==1.0.0
      - graphlib-backport==1.1.0
      - grpcio==1.70.0
      - gseapy==1.1.10
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - igraph==0.11.8
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - importlib-resources==6.4.5
      - interface-meta==1.3.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==2.13.1
      - kiwisolver==1.4.7
      - latex2mathml==3.77.0
      - libclang==18.1.1
      - lifelines==0.27.8
      - llvmlite==0.41.1
      - louvain==0.8.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - mygene==3.2.2
      - natsort==8.4.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - packaging==24.1
      - pandas==2.0.3
      - patsy==1.0.1
      - pillow==10.4.0
      - pooch==1.8.2
      - propcache==0.2.0
      - protobuf==4.25.6
      - psutil==6.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scanpy==1.9.8
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - session-info==1.0.1
      - shap==0.44.1
      - slicer==0.0.7
      - sniffio==1.3.1
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - sympy==1.13.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - torch-geometric==2.6.1
      - tqdm==4.67.0
      - triton==3.0.0
      - typing-extensions==4.5.0
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/common/xwzhang/miniconda3/envs/Bio
